### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by vivekgidmare** [appcelerator/movies#2]
Steps 
Movies category -> Click on any category(Now Playing)->Click Device Back Button 2 times to come out of app.
Movies App gets crashed.Try 2 to 3 times will generate this crash.

Logs :
3-11 18:14:26.479: E/AndroidRuntime(2758): FATAL EXCEPTION: main
03-11 18:14:26.479: E/AndroidRuntime(2758): Process: com.appcelerator.movies, PID: 2758
03-11 18:14:26.479: E/AndroidRuntime(2758): java.lang.NullPointerException
03-11 18:14:26.479: E/AndroidRuntime(2758):     at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:316)
03-11 18:14:26.479: E/AndroidRuntime(2758):     at android.os.Handler.dispatchMessage(Handler.java:98)
03-11 18:14:26.479: E/AndroidRuntime(2758):     at android.os.Looper.loop(Looper.java:136)
03-11 18:14:26.479: E/AndroidRuntime(2758):     at android.app.ActivityThread.main(ActivityThread.java:5001)
03-11 18:14:26.479: E/AndroidRuntime(2758):     at java.lang.reflect.Method.invokeNative(Native Method)
03-11 18:14:26.479: E/AndroidRuntime(2758):     at java.lang.reflect.Method.invoke(Method.java:515)
03-11 18:14:26.479: E/AndroidRuntime(2758):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)

**Comment by lowski** [comment]
For me app doesn't even want to start on Android:

```
-- Start application log -----------------------------------------------------
[INFO]  TiApplication: (main) [0,0] checkpoint, app created.
[INFO]  TiApplication: (main) [17,17] Titanium 5.0.0 (2015/09/15 23:07 ec79bc5)
[INFO]  DatabaseHelper: No value in database for platform key: 'unique_machine_id' returning supplied default ''
[INFO]  DatabaseHelper: No value in database for platform key: 'hardware_machine_id' returning supplied default ''
[INFO]  TiApplication: (main) [98,115] Titanium Javascript runtime: v8
[INFO]  TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[INFO]  TiApplication: (main) [1,1] Analytics have been disabled
[WARN]  V8Object: (KrollRuntimeThread) [31,32] Runtime disposed, cannot set property 'userAgent'
[DEBUG] AndroidRuntime: Shutting down VM
[DEBUG] Module: Loading module: alloy -> Resources/alloy.js
[DEBUG] Module: Loading module: alloy/underscore -> Resources/alloy/underscore.js
[DEBUG] Module: Loading module: alloy/backbone -> Resources/alloy/backbone.js
[DEBUG] Module: Loading module: alloy/constants -> Resources/alloy/constants.js
[DEBUG] Module: Loading module: alloy/CFG -> Resources/alloy/CFG.js
[DEBUG] Module: Loading module: alloy/controllers/index -> Resources/alloy/controllers/index.js
[DEBUG] Module: Loading module: alloy/controllers/BaseController -> Resources/alloy/controllers/BaseController.js
[DEBUG] Module: Loading module: alloy/controllers/intro -> Resources/alloy/controllers/intro.js
[INFO]  Process: Sending signal. PID: 1940 SIG: 9
-- End application log -------------------------------------------------------
```

**Comment by trkfabi** [comment]
Same here. It doesn't start on Android. Same error as @lowski

**Comment by grantges** [comment]
we fixed some things with Android a while back - are you all still seeing this crash?

**Comment by hansemannn** [comment]
Not reproducible in latest SDK anymore
