### ISSUE TITLE
Can Some Explain The License

### ISSUE THREAD

**Issue by samueleastdev** [appcelerator/movies#22]
Hi All,

Can someone please explain the license for this app I see it is an example app to get started with Appcelerator and I was thinking about using it as a template for one of my projects but after reading the license I am not sure if this is a good idea and was wonder if someone could clarify that I could use this free of charge? 

https://github.com/appcelerator/movies/blob/master/LICENSE

Does this section

> "Legal Entity" shall mean the union of the acting entity and all
>       other entities that control, are controlled by, or are under common
>       control with that entity. For the purposes of this definition,
>       "control" means (i) the power, direct or indirect, to cause the
>       direction or management of such entity, whether by contract or
>       otherwise, or (ii) ownership of fifty percent (50%) or more of the
>       outstanding shares, or (iii) beneficial ownership of such entity.

mean that if I built my project from this example app or used any of the code then the app would be 50% owned by Appcelerator just curious there is no point me using this if this is the case and I am happy to build my app from scratch but thought it was worth asking first would save me a tonne of time using this?

**Comment by ewanharris** [comment]
Hey @samueleastdev,

The license here exists specifically allow the kind of usage you're asking for.
It allows you to fork this project and build on top of it without having to worry about us claiming the existing code under copyright.
The only requirements are outlined in the [license file](https://github.com/appcelerator/movies/blob/8f86ade59581ccd830d27a60024c3efe62728fac/LICENSE#L94-L133), or a little simpler [here](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)).
The TL;DR is:

- Any files that have a copyright header for Appcelerator must be kept that way i.e you can't remove the Appcelerator claim. However code you add yourself is yours.
- Files you create are wholly owned by yourself, and can be licensed as you wish (as long as the license is compatible).
- If you open source the forked sample app, you must indicate that Appcelerator is the originator of certain code (the license tells you how to indicate that).

I hope that helps, if you have any other questions feel free to ask away!

**Comment by samueleastdev** [comment]
Brilliant that should save me some thanks for the info ;)
