### ISSUE TITLE
undefined is not a function (evaluating '$.searchCell.updateViews')

### ISSUE THREAD

**Issue by pphan** [appcelerator/movies#3]
When I run on iOS simulator, I got like this error at below 

[ERROR] :  Script Error {
[ERROR] :      column = 33;
[ERROR] :      line = 35;
[ERROR] :      message = "undefined is not a function (evaluating '$.searchCell.updateViews')";
[ERROR] :  }

**Comment by fridayforward** [comment]
@pphan I'm not able to reproduce. Which version of the Titanium SDK are you using? This method was introduced in Alloy 1.4.0 / Ti 3.3.0.

**Comment by moreli** [comment]
I've getting a similar issue when using: resetClass
$.resetClass($.website_button, 'link_button_2');

I've pasted the modifications I made to the movie controller here http://pastebin.com/QS7mLDse

I've noticed it in another app i'm working on, and i'm not sure whether this is an appcelerator bug or bug in this app.
Tested with both 3.5.1 and 4.0.0.RC4.

[ERROR] :  Script Error {
[ERROR] :      column = 864;
[ERROR] :      line = 1;
[ERROR] :      message = "undefined is not an object (evaluating 'Ti.UI.ActivityIndicatorStyle.BIG')";

**Comment by hansemannn** [comment]
Not reproducible in latest SDK anymore
