### ISSUE TITLE
How would the movies app be unit tested?

### ISSUE THREAD

**Issue by albemuth** [appcelerator/movies#5]
Could we get some examples of how to unit test parts of this application, how about asserting the number of lists created and that tapping on one of them performs the appropriate action. It's not straight forward to understand how to go from the example on the [ti-mocha](http://tonylukasavage.com/ti-mocha/#using-shouldjs-with-ti-mocha) homepage to an app like this one.

**Comment by hansemannn** [comment]
You would use ti-mocha indeed. We can add some unit tests in Q1, just follow this ticket!
