### ISSUE TITLE
Navigator goHome results in error

### ISSUE THREAD

**Issue by moreli** [appcelerator/movies#6]
Hello, getting an error when trying to use the goHome function from the navigator library
[ERROR] :  Script Error {
[ERROR] :      column = 41;
[ERROR] :      line = 38;
[ERROR] :      message = "undefined is not an object (evaluating 'that.currentController.navWindow.close')";
[ERROR] :      sourceURL = "file:.../navigation.js";
This is with multiple SDKs on an iOS simulator for iPhone 5S.

Any advice?

**Comment by fridayforward** [comment]
Hi @moreli. The Navigator.goHome() method is not used in Movies and contains out of date code. I'll remove it in a future update. Sorry about that.
